### ISSUE TITLE
Click not working in the game.  

### ISSUE THREAD

**Issue by optimusam** [optimusam/colorgame#3]
Recent merge broke the game functionality. Click isn't working. Feel free to contribute in fixing.

**Comment by rcass** [comment]
Can I take this one on?

**Comment by heyseth** [comment]
#4  my fix. Sorry, should I have asked first?

**Comment by jgrrdnd** [comment]
Hi, can I work on this?

**Comment by rcass** [comment]
@Fantop Whoops totally just saw your message... right after I submitted my PR #5  

I guess we both have solutions 🤷‍♀️

**Comment by heyseth** [comment]
@rcass my bad, lesson learned 😁

**Comment by optimusam** [comment]
Thanks for the help guys.
